-- MySQL Script generated by MySQL Workbench
-- Tue Dec  4 21:11:53 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dekanat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dekanat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dekanat` DEFAULT CHARACTER SET utf8 ;
USE `dekanat` ;

-- -----------------------------------------------------
-- Table `dekanat`.`Groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dekanat`.`Groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dekanat`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dekanat`.`Students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `group` INT NOT NULL,
  `full_name` VARCHAR(255) NOT NULL,
  `birthdate` DATE NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC),
  INDEX `student_2_group_idx` (`group` ASC),
  CONSTRAINT `student_2_group`
    FOREIGN KEY (`group`)
    REFERENCES `dekanat`.`Groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dekanat`.`Subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dekanat`.`Subjects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dekanat`.`Grades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dekanat`.`Grades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  `grade` INT(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `grade_2_student_idx` (`student_id` ASC),
  INDEX `grade_2_subject_idx` (`subject_id` ASC),
  CONSTRAINT `grade_2_student`
    FOREIGN KEY (`student_id`)
    REFERENCES `dekanat`.`Students` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `grade_2_subject`
    FOREIGN KEY (`subject_id`)
    REFERENCES `dekanat`.`Subjects` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
